-- Ejecutar en Supabase SQL Editor.
-- Crea la tabla usada por /mantenimientos/tasa-itbis.

begin;

create table if not exists myappdb.itbis (
  id int4 generated by default as identity primary key,
  codigo varchar(20) not null,
  descripcion varchar(100) not null,
  porcentaje numeric(10, 4) not null default 0,
  porcentaje_menos numeric(10, 4) not null default 0,
  nivel varchar(20) not null default 'General',
  estado varchar(12) not null default 'Activo',
  fecha_inicio date not null default current_date,
  fecha_fin date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists myappdb.itbis
  add column if not exists codigo varchar(20),
  add column if not exists descripcion varchar(100),
  add column if not exists porcentaje numeric(10, 4) default 0,
  add column if not exists porcentaje_menos numeric(10, 4) default 0,
  add column if not exists nivel varchar(20) default 'General',
  add column if not exists estado varchar(12) default 'Activo',
  add column if not exists fecha_inicio date default current_date,
  add column if not exists fecha_fin date,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'myappdb'
      and table_name = 'itbis'
      and column_name = 'nive'
  ) then
    update myappdb.itbis
    set nivel = coalesce(nullif(trim(nivel), ''), nullif(trim(nive), ''), 'General')
    where nivel is null or trim(nivel) = '';
  end if;
end $$;

update myappdb.itbis
set nivel = 'General'
where nivel is null or trim(nivel) = '';

alter table myappdb.itbis
  alter column codigo set not null,
  alter column descripcion set not null,
  alter column porcentaje set not null,
  alter column porcentaje_menos set not null,
  alter column nivel set not null,
  alter column estado set not null,
  alter column fecha_inicio set not null;

create unique index if not exists ux_itbis_codigo
  on myappdb.itbis (codigo);

create index if not exists idx_itbis_estado
  on myappdb.itbis (estado);

create unique index if not exists ux_itbis_nivel_activo
  on myappdb.itbis (lower(nivel))
  where lower(estado) = 'activo';

drop trigger if exists trg_itbis_calculados on myappdb.itbis;
drop function if exists myappdb.set_itbis_calculados();

insert into myappdb.itbis (codigo, descripcion, porcentaje, porcentaje_menos, nivel, estado, fecha_inicio)
values
  ('ITBIS-01', 'ITBIS General', 18, 15.2542, 'General', 'Activo', '2024-01-01'),
  ('ITBIS-02', 'ITBIS Reducido', 16, 13.7931, 'Reducido', 'Activo', '2024-01-01'),
  ('ITBIS-03', 'ITBIS 0% (Exento)', 0, 0, 'Exento', 'Activo', '2024-01-01')
on conflict (codigo)
do update
set
  descripcion = excluded.descripcion,
  porcentaje = excluded.porcentaje,
  porcentaje_menos = excluded.porcentaje_menos,
  nivel = excluded.nivel,
  estado = excluded.estado,
  fecha_inicio = excluded.fecha_inicio;

grant usage on schema myappdb to anon, authenticated;
grant select, insert, update, delete on table myappdb.itbis to anon, authenticated;
grant usage, select on all sequences in schema myappdb to anon, authenticated;

alter table myappdb.itbis enable row level security;

drop policy if exists itbis_select_frontend on myappdb.itbis;
drop policy if exists itbis_insert_frontend on myappdb.itbis;
drop policy if exists itbis_update_frontend on myappdb.itbis;
drop policy if exists itbis_delete_frontend on myappdb.itbis;

create policy itbis_select_frontend
on myappdb.itbis
for select
to anon, authenticated
using (true);

create policy itbis_insert_frontend
on myappdb.itbis
for insert
to anon, authenticated
with check (true);

create policy itbis_update_frontend
on myappdb.itbis
for update
to anon, authenticated
using (true)
with check (true);

create policy itbis_delete_frontend
on myappdb.itbis
for delete
to anon, authenticated
using (true);

commit;

notify pgrst, 'reload schema';
