create table if not exists myappdb.solicitud (
  so_numero varchar(12) primary key,
  so_fecha date not null default current_date,
  so_codclie varchar(10),
  so_nomclie varchar(80),
  so_sucursal_clie varchar(80),
  so_solicitante varchar(60),
  so_observacion varchar(250),
  so_status varchar(4) default 'A',
  so_codempr varchar(10),
  so_codsucu int4
);

alter table if exists myappdb.solicitud
  add column if not exists so_numero varchar(12),
  add column if not exists so_fecha date default current_date,
  add column if not exists so_codclie varchar(10),
  add column if not exists so_nomclie varchar(80),
  add column if not exists so_sucursal_clie varchar(80),
  add column if not exists so_solicitante varchar(60),
  add column if not exists so_observacion varchar(250),
  add column if not exists so_status varchar(4) default 'A',
  add column if not exists so_codempr varchar(10),
  add column if not exists so_codsucu int4;

create table if not exists myappdb.detsolicitud (
  id int4 generated by default as identity primary key,
  ds_numero varchar(12) not null,
  ds_codmerc varchar(15) not null,
  ds_desmerc varchar(80),
  ds_canmerc numeric(12, 2) not null default 0,
  ds_unidad varchar(12),
  constraint detsolicitud_ds_numero_fkey
    foreign key (ds_numero)
    references myappdb.solicitud (so_numero)
    on delete cascade
);

alter table if exists myappdb.detsolicitud
  add column if not exists ds_numero varchar(12),
  add column if not exists ds_codmerc varchar(15),
  add column if not exists ds_desmerc varchar(80),
  add column if not exists ds_canmerc numeric(12, 2) default 0,
  add column if not exists ds_unidad varchar(12);

create index if not exists idx_solicitud_fecha on myappdb.solicitud (so_fecha);
create index if not exists idx_solicitud_cliente on myappdb.solicitud (so_codclie, so_nomclie);
create index if not exists idx_detsolicitud_numero on myappdb.detsolicitud (ds_numero);
