-- Ejecutar en Supabase SQL Editor.
-- Crea la tabla usada por /mantenimientos/precio para historial de cambios.

begin;

create table if not exists myappdb.precio (
  id int8 generated by default as identity primary key,
  codigo varchar(50) not null,
  descripcion varchar(255),
  precioactual numeric(18, 2) not null default 0,
  precionuevo numeric(18, 2) not null default 0,
  fechacambio timestamptz not null default now(),
  status varchar(12) not null default 'A'
);

alter table if exists myappdb.precio
  add column if not exists codigo varchar(50),
  add column if not exists descripcion varchar(255),
  add column if not exists precioactual numeric(18, 2) default 0,
  add column if not exists fechacambio timestamptz default now(),
  add column if not exists status varchar(12) default 'A';

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'myappdb'
      and table_name = 'precio'
      and column_name = 'precioant'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'myappdb'
      and table_name = 'precio'
      and column_name = 'precionuevo'
  ) then
    alter table myappdb.precio rename column precioant to precionuevo;
  end if;
end $$;

alter table if exists myappdb.precio
  add column if not exists precionuevo numeric(18, 2) default 0;

update myappdb.precio
set
  codigo = upper(trim(coalesce(codigo, ''))),
  descripcion = nullif(trim(coalesce(descripcion, '')), ''),
  precioactual = coalesce(precioactual, 0),
  precionuevo = coalesce(precionuevo, 0),
  fechacambio = coalesce(fechacambio, now()),
  status = coalesce(nullif(trim(status), ''), 'A');

alter table myappdb.precio
  alter column codigo set not null,
  alter column precioactual set not null,
  alter column precionuevo set not null,
  alter column fechacambio set not null,
  alter column status set not null;

create index if not exists idx_precio_codigo
  on myappdb.precio (codigo);

create index if not exists idx_precio_fechacambio
  on myappdb.precio (fechacambio desc);

create index if not exists idx_precio_status
  on myappdb.precio (status);

grant usage on schema myappdb to anon, authenticated;
grant select, insert, update, delete on table myappdb.precio to anon, authenticated;
grant usage, select on all sequences in schema myappdb to anon, authenticated;

alter table myappdb.precio enable row level security;

drop policy if exists precio_select_frontend on myappdb.precio;
drop policy if exists precio_insert_frontend on myappdb.precio;
drop policy if exists precio_update_frontend on myappdb.precio;
drop policy if exists precio_delete_frontend on myappdb.precio;

create policy precio_select_frontend
on myappdb.precio
for select
to anon, authenticated
using (true);

create policy precio_insert_frontend
on myappdb.precio
for insert
to anon, authenticated
with check (true);

create policy precio_update_frontend
on myappdb.precio
for update
to anon, authenticated
using (true)
with check (true);

create policy precio_delete_frontend
on myappdb.precio
for delete
to anon, authenticated
using (true);

commit;

notify pgrst, 'reload schema';
